###############################################################
# Render Blueprint – backend + Expo static site
###############################################################
services:
  - type: web
    name: delivery-backend
    env: docker
    rootDir: backend
    plan: free
    region: frankfurt
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
